### ISSUE TITLE
Call to undefined function CodeIgniter\Autoloader\token_get_all()

### ISSUE THREAD

**Issue by egrueda** [helpdesk-z/helpdeskz-dev#1]
PHP 7.3 fresh install, cant find tokenizer methods.
Is this a required php module?

```
[16-Jan-2021 08:57:31 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function CodeIgniter\Autoloader\token_get_all() in /var/www/helpdeskz/public/hdz/framework/Autoloader/FileLocator.php:173
Stack trace:
#0 /var/www/helpdeskz/public/hdz/framework/Config/Config.php(150): CodeIgniter\Autoloader\FileLocator->getClassname('/var/www/helpde...')
#1 /var/www/helpdeskz/public/hdz/framework/Config/Config.php(83): CodeIgniter\Config\Config::createClass('Modules')
#2 /var/www/helpdeskz/public/hdz/framework/Common.php(155): CodeIgniter\Config\Config::get('Modules', true)
#3 /var/www/helpdeskz/public/hdz/framework/Config/BaseConfig.php(85): config('Modules')
#4 /var/www/helpdeskz/public/hdz/framework/Config/Config.php(124): CodeIgniter\Config\BaseConfig->__construct()
#5 /var/www/helpdeskz/public/hdz/framework/Config/Config.php(83): CodeIgniter\Config\Config::createClass('Config\\App')
#6 /var/www/helpdeskz/public/hdz/framework/Common.php(155): CodeIgniter\Config\Config::get('Config\\App', true)
#7 /var/www/helpdeskz/public/hdz/framework/bootstrap.php(179) in /var/www/helpdeskz/public/hdz/framework/Autoloader/FileLocator.php on line 173

```

**Comment by helpdesk-z** [comment]
Hi,
Yes, I check the codeigniter forum and it is required to be installed in your hosting: https://www.php.net/manual/en/book.tokenizer.php
Here is a discussion about it: https://forum.codeigniter.com/thread-77038.html

I'm uploading the script in PHP 7.3 to reproduce your error, so I'm going to update it in a moment.
(Si deseas, hablamos español)

**Comment by helpdesk-z** [comment]
I have enabled Tokenizer and works without any problem in PHP 7.3.

**Comment by egrueda** [comment]
¡Gracias!
It was installed but not enabled.
In Debian I did:
`phpenmod -v ALL -s fpm tokenizer`
Maybe you can point that in the requirement section

**Comment by helpdesk-z** [comment]
Gracias a ti, servirá de mucho para otros usuarios.
