### ISSUE TITLE
PHP IMAP

### ISSUE THREAD

**Issue by superwojciech** [helpdesk-z/helpdeskz-dev#73]
What I can do?
Php8.1

after running **/usr/local/bin/php /var/www/html/new/helpdesk/index.php imap_fetcher**

_ERROR - 2024-01-20 07:16:14 --> IMAP connection failed: InvalidArgumentException: Argument 1 passed to PhpImap\Imap::search must be a valid resource! in /var/www/html/new/helpdesk/hdz/vendor/php-imap/php-imap/src/PhpImap/Imap.php:1077
Stack trace:
#0 /var/www/html/new/helpdesk/hdz/vendor/php-imap/php-imap/src/PhpImap/Imap.php(1094): PhpImap\Imap::EnsureResource()
#1 /var/www/html/new/helpdesk/hdz/vendor/php-imap/php-imap/src/PhpImap/Imap.php(821): PhpImap\Imap::EnsureConnection()
#2 /var/www/html/new/helpdesk/hdz/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(621): PhpImap\Imap::search()
#3 /var/www/html/new/helpdesk/hdz/app/Libraries/MailFetcher.php(38): PhpImap\Mailbox->searchMailbox()
#4 /var/www/html/new/helpdesk/hdz/app/Controllers/MailFetcher.php(16): App\Libraries\MailFetcher->parse_imap()
#5 /var/www/html/new/helpdesk/hdz/framework/CodeIgniter.php(936): App\Controllers\MailFetcher->imap()
#6 /var/www/html/new/helpdesk/hdz/framework/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController()
#7 /var/www/html/new/helpdesk/hdz/framework/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest()
#8 /var/www/html/new/helpdesk/index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}

Next PhpImap\Exceptions\ConnectionException: Argument 1 passed to PhpImap\Imap::search must be valid resource! in /var/www/html/new/helpdesk/hdz/vendor/php-imap/php-imap/src/PhpImap/Imap.php:1096
Stack trace:
#0 /var/www/html/new/helpdesk/hdz/vendor/php-imap/php-imap/src/PhpImap/Imap.php(821): PhpImap\Imap::EnsureConnection()
#1 /var/www/html/new/helpdesk/hdz/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(621): PhpImap\Imap::search()
#2 /var/www/html/new/helpdesk/hdz/app/Libraries/MailFetcher.php(38): PhpImap\Mailbox->searchMailbox()
#3 /var/www/html/new/helpdesk/hdz/app/Controllers/MailFetcher.php(16): App\Libraries\MailFetcher->parse_imap()
#4 /var/www/html/new/helpdesk/hdz/framework/CodeIgniter.php(936): App\Controllers\MailFetcher->imap()
#5 /var/www/html/new/helpdesk/hdz/framework/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController()
#6 /var/www/html/new/helpdesk/hdz/framework/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest()
#7 /var/www/html/new/helpdesk/index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}_

**Comment by cassiodoroVicinetti** [comment]
Duplicate #68
